---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/
- Containers:
    - HomeLab:
        href: http://kstrugal.local:3000
        description: HomeLab dashboard
        icon: homepage
        ping: http://kstrugal.local:3000
    - Portainer:
        href: https://kstrugal.local:9443/#!/3/docker/dashboard
        description: Containers management GUI
        icon: portainer
        ping: https://kstrugal.local:9443

- Monitoring:
    - Kuma Uptime:
        href: http://kstrugal.local:3001
        description: Kuma Uptime
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/uptime-kuma.svg

