
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/
- Containers:
    - HomeLab:
        href: http://192.168.43.44:3000
        description: HomeLab dashboard
        icon: homepage
    - Portainer:
        href: https://192.168.43.44:9443/#!/3/docker/dashboard
        description: Containers management GUI
        icon: portainer
        container: portainer
    - Cockpit:
        href: https://192.168.43.44:9090
        description: Server GUI manager
        icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/cockpit.png

- Monitoring:
    - Kuma Uptime:
        href: http://192.168.43.44:3001
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/uptime-kuma.svg
        container: uptime-kuma
    - Grafana:
        href: http://192.168.43.44:3002
        icon: grafana
        container: grafana

- Networking:
    - Pihole:
        href: https://192.168.43.44/admin/
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/pi-hole.svg
    - Nginx Proxy Manager:
        href: http://192.168.43.44:81
        icon: nginx
