
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/
- Containers:
    - HomeLab:
        href: http://192.168.43.44:3000
        description: HomeLab dashboard
        icon: homepage
        ping: http://192.168.43.44:3000
    - Portainer:
        href: https://192.168.43.44:9443/#!/3/docker/dashboard
        description: Containers management GUI
        icon: portainer
        ping: http://192.168.43.44:9443

- Monitoring:
    - Kuma Uptime:
        href: http://192.168.43.44:3001
        description: Kuma Uptime
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/uptime-kuma.svg
    - Grafana:
        href: http://192.168.43.44:3002
        icon: grafana

- Networking:
    - Pihole:
        href: https://192.168.43.44/admin/
        description: Pihole
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/pi-hole.svg
