---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: "Kacper HomeLab"

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
